name: Get Flag
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  get-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: 70ecc0a4-b071-406f-9e39-a39e9939940a
          tenant-id: fdd066e1-ee37-49bc-b08f-d0e152119b04
          subscription-id: f89fc1d7-0449-4b52-bdd7-804f53711a6f
          enable-AzPSSession: true

      - name: Download flag
        run: |
          az storage blob download \
            --account-name iamazurelab3331fa542 \
            --container-name flag \
            --name flag.txt \
            --file flag.txt \
            --auth-mode login
      - name: Read flag
        run: |
          cat flag.txt
