name: Azure Login with Managed Identity

permissions:
  id-token: write  # Grant permission to write the ID token
  contents: read   # Read repository contents

on:
  push:
    branches:
      - main

jobs:
  azure-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login with Managed Identity
        uses: azure/login@v1
        with:
          client-id: c233bf84-6353-4e44-add5-88e57659b353
          tenant-id: fdd066e1-ee37-49bc-b08f-d0e152119b04
          subscription-id: 201d0ac0-9452-4197-9f2e-d3bb2f3c42b3
          auth-type: SERVICE_PRINCIPAL  # Explicitly use service principal authentication

      - name: List Storage Blob
        run: |
          az storage blob list --account-name iamazurelab2331fa542 --container-name flag --auth-mode login
